// filepath: /c:/Users/guicota/Desktop/MEI/odsoft-project-2024/P2/apps/Books/BooksC/Jenkinsfile
pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
        DOCKER_IMAGE = 'books-q-image'
        DOCKER_REGISTRY = 'docker.io/jazzmattaz'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    docker.build("${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push') {
            steps {
                script {
                    docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_CREDENTIALS_ID}") {
                        docker.image("${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest").push()
                    }
                }
            }
        }

      //  stage('Deploy') {
      //      steps {
      //          script {
      //              sh 'docker stack deploy -c ../../books-query.yml books-query'
      //          }
      //     }
      //  }

        stage('Test') {
            steps {
                script {
                    // Add your test steps here
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            sh 'docker system prune -f'
        }
        success {
            mail to: '1190640@isep.ipp.pt',
                 subject: "Deployment Successful: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                 body: "The deployment of ${env.JOB_NAME} [${env.BUILD_NUMBER}] was successful."
        }
        failure {
            mail to: '1190640@isep.ipp.pt',
                 subject: "Deployment Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                 body: "The deployment of ${env.JOB_NAME} [${env.BUILD_NUMBER}] failed. Please check the Jenkins logs for more details."
        }
    }
}