version: '3.8'


services:

  nginx:
    image: nginx
    restart: unless-stopped
    mem_limit: 256m
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  network:
    external: true