version: '3.8'

volumes:
  mongo-initdb:

services:
  # Instance 1 (Command)
  booksC-1:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ${BOOKS_COMMAND_BUILD_CONTEXT}
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_RESTART_POLICY}
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_1}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - ${NETWORK_NAME}

  db-booksC-1:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_DB_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_DB_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_DB_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_DB_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_DB_RESTART_POLICY}
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - ${NETWORK_NAME}

  mongo-express-books-1:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${BOOKS_COMMAND_MONGO_EXPRESS_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_MONGO_EXPRESS_RESTART_POLICY}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_1}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_1}
        protocol: tcp
        mode: host
    networks:
      - network

  # Additional instances follow the same structure
  booksC-2:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ${BOOKS_COMMAND_BUILD_CONTEXT}
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_RESTART_POLICY}
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_2}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - ${NETWORK_NAME}

  db-booksC-2:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_DB_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_DB_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_DB_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_DB_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_DB_RESTART_POLICY}
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - ${NETWORK_NAME}

  mongo-express-books-2:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${BOOKS_COMMAND_MONGO_EXPRESS_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_MONGO_EXPRESS_RESTART_POLICY}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_2}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_2}
        protocol: tcp
        mode: host
    networks:
      - ${NETWORK_NAME}

  booksC-3:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ${BOOKS_COMMAND_BUILD_CONTEXT}
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_RESTART_POLICY}
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_3}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - ${NETWORK_NAME}

  db-booksC-3:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${BOOKS_COMMAND_DB_CPU_LIMIT}
          memory: ${BOOKS_COMMAND_DB_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_DB_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_DB_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_DB_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_DB_RESTART_POLICY}
    environment:
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - ${NETWORK_NAME}

  mongo-express-books-3:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${BOOKS_COMMAND_MONGO_EXPRESS_MEMORY_LIMIT}
      update_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_UPDATE_DELAY}
      rollback_config:
        parallelism: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_PARALLELISM}
        delay: ${BOOKS_COMMAND_MONGO_EXPRESS_ROLLBACK_DELAY}
      restart_policy:
        condition: ${BOOKS_COMMAND_MONGO_EXPRESS_RESTART_POLICY}
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_3}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_3}
        protocol: tcp
        mode: host
    networks:
      - ${NETWORK_NAME}
networks:
  ${NETWORK_NAME}:
    external: true
