version: '3.8'

volumes:
  mongo-initdb:

services:
  # Instance 1 (Command)
  booksC-1:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ../apps/Books/BooksC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_1}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-booksC-1:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-books-1:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_1}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_1}
        protocol: tcp
        mode: host
    networks:
      - network


  # Additional instances follow the same structure
  booksC-2:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ../apps/Books/BooksC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_2}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-booksC-2:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-books-2:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_2}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_2}
        protocol: tcp
        mode: host
    networks:
      - network

  booksC-3:
    image: ${BOOKS_COMMAND_IMAGE}
    build: 
      context: ../apps/Books/BooksC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      SPRING_DATA_DB_HOST: ${BOOKS_COMMAND_SPRING_DATA_DB_HOST_3}
      SPRING_DATA_DATABASE_TYPE: ${BOOKS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-booksC-3:
    image: ${BOOKS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-books-3:
    image: ${BOOKS_COMMAND_MONGO_EXPRESS_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=${BOOKS_COMMAND_ME_CONFIG_MONGODB_SERVER_3}
      - ME_CONFIG_BASICAUTH_USERNAME=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${BOOKS_COMMAND_ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - target: ${BOOKS_COMMAND_MONGO_EXPRESS_TARGET_PORT}
        published: ${BOOKS_COMMAND_MONGO_EXPRESS_PUBLISHED_PORT_3}
        protocol: tcp
        mode: host
    networks:
      - network

networks:
  network:
    external: true
