version: '3.8'

volumes:
  mongo-initdb:

services:
  # Instance 1 (Command)
  lendingsC-1:
    image: ${LENDINGS_COMMAND_IMAGE}
    build:
      context: ../apps/Lendings/LendingsC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:29092, kafka2:29093, kafka3:29094
      SPRING_DATA_DB_HOST: db-lendingsC-1
      SPRING_DATA_DATABASE_TYPE: ${LENDINGS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-lendingsC-1:
    image: ${LENDINGS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-lendings-1:
    image: mongo-express:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-lendingsC-1
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - target: 8081
        published: 8094
        protocol: tcp
        mode: host
    networks:
      - network

  # Additional instances follow the same structure
  lendingsC-2:
    image: ${LENDINGS_COMMAND_IMAGE}
    build:
      context: ../apps/Lendings/LendingsC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:29092, kafka2:29093, kafka3:29094
      SPRING_DATA_DB_HOST: db-lendingsC-2
      SPRING_DATA_DATABASE_TYPE: ${LENDINGS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-lendingsC-2:
    image: ${LENDINGS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-lendings-2:
    image: mongo-express:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-lendingsC-2
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - target: 8081
        published: 8095
        protocol: tcp
        mode: host
    networks:
      - network

  lendingsC-3:
    image: ${LENDINGS_COMMAND_IMAGE}
    build:
      context: ../apps/Lendings/LendingsC
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:29092, kafka2:29093, kafka3:29094
      SPRING_DATA_DB_HOST: db-lendingsC-3
      SPRING_DATA_DATABASE_TYPE: ${LENDINGS_COMMAND_DATABASE_TO_USE}
      ID_GENERATOR: ${ID_GENERATOR}
      RECOMMENDATION_ALGORITHM: ${RECOMMENDATION_ALGORITHM}
      RECOMMENDATION_X: ${RECOMMENDATION_X}
      RECOMMENDATION_Y: ${RECOMMENDATION_Y}
      MINIMUM_AGE: ${MINIMUM_AGE}
      MAXIMUM_AGE: ${MAXIMUM_AGE}
    networks:
      - network

  db-lendingsC-3:
    image: ${LENDINGS_COMMAND_DATABASE_IMAGE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo-initdb:/docker-entrypoint-initdb.d/
    networks:
      - network

  mongo-express-lendings-3:
    image: mongo-express:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
    environment:
      - ME_CONFIG_MONGODB_SERVER=db-lendingsC-3
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - target: 8081
        published: 8096
        protocol: tcp
        mode: host
    networks:
      - network
networks:
  network:
    external: true
