version: '3.8'

services:
  mongoDB-bootstrap:
    image: mongo:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: events
    volumes:
      - mongo-init-scripts:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    networks:
      - network

  populateDBs:
    image: populate-dbs-image:latest
    build: ../../apps/Bootstrapper
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: none
    depends_on:
      - mongoDB-bootstrap
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:29092, kafka2:29093, kafka3:29094
      SPRING_DATA_MONGODB_DATABASE: events
      SPRING_DATA_MONGODB_HOST: mongoDB-bootstrap
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin
    networks:
      - network

  mongo-express-review-1:
    image: mongo-express:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: none
    depends_on:
      - mongoDB-bootstrap
    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB-bootstrap
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - target: 8081
        published: 8060
        protocol: tcp
        mode: host
    networks:
      - network

volumes:
  mongo-init-scripts:
    driver: local
  mongo-data:
    driver: local

networks:
  network:
    external: true
